
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpvgvqrfutmbbaigvgyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdmd2cXJmdXRtYmJhaWd2Z3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDQ1NzIsImV4cCI6MjA2MjcyMDU3Mn0._AIsIQX4jn5mER0lpNdG3aC92KfH7g1j-vPHF0gc1xI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
